/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDTO } from './userResponseDTO';
import { MessageResponseDTO } from './messageResponseDTO';


export interface ConversationResponseDTO { 
    id: number;
    createdAt: string;
    updatedAt: string;
    participants: Array<UserResponseDTO>;
    messages: Array<MessageResponseDTO>;
}

