/**
 * Chat - API
 * Chat - API Description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserResponseDTO } from './userResponseDTO';


export interface MessageResponseDTO { 
    id: number;
    createdAt: string;
    updatedAt: string;
    content: string;
    author: UserResponseDTO;
}

